### ISSUE TITLE
24:01 + 70min = 25:11

### ISSUE THREAD

**Issue by kdzwinel** [paulirish/caltrainschedule.io#10]
<img width="246" alt="screen shot 2016-05-24 at 13 46 19" src="https://cloud.githubusercontent.com/assets/985504/15502718/02e1c23a-21b6-11e6-97cc-c2f77ed284bd.png">

Should be 00:01 + 70min = 01:11

**Comment by samccone** [comment]
@paulirish almost got a math degree FYI
