### ISSUE TITLE
sweet onboarding flow

### ISSUE THREAD

**Issue by paulirish** [paulirish/caltrainschedule.io#12]
wit dat money yo

**Comment by paulirish** [comment]
now the initial state is this:

![image](https://cloud.githubusercontent.com/assets/39191/23444080/a7b96214-fde7-11e6-9739-315ab05b0570.png)

One basic solution to onboarding is a basic text link to prefill with a hardcoded choice.

> [For example: Palo Alto <--> San Francisco](#)

(see also the research in #7 for choosing stations)

**Comment by samccone** [comment]
geolocation :]

**Comment by samccone** [comment]
yay \o/
