### ISSUE TITLE
update data

### ISSUE THREAD

**Issue by paulirish** [paulirish/caltrainschedule.io#14]
they have new data

 http://www.caltrain.com/about/MediaRelations/news/Caltrain_to_Swap_Train_Sets_This_Month_for_More_Capacity_and_Maintenance.html
trains 134, 155, 217, and 268 are bombardier

in the rakefile we'll have to bump `'2016APR_GTFS'` to `'2016APR_GTFS_rev2'` and probably a few other things

**Comment by samccone** [comment]
:+1:
