### ISSUE TITLE
exception Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode

### ISSUE THREAD

**Issue by paulirish** [paulirish/caltrainschedule.io#49]
firing from here

https://github.com/paulirish/caltrainschedule.io/blob/ca3b7af208b8ac1012a5a40c79b79c16821b6465/sw.js#L40

**Comment by paulirish** [comment]
this `only-if-cached` [`e.request.cache` state](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache) is seemingly set when you open devtools and, i guess, devtools triggers a fetch of the document to show. the SW catches this but it can't actually make the real fetch.

see MDN saying

> The "only-if-cached" mode can only be used if the request's mode is "same-origin".

**Comment by jakearchibald** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=823392
